export const mockRateCardsResponse = {
  data: {
    UpSellItemList: [
      {
        IsBestValue: true,
        CategoryID: 0,
        OriginalPrice: 23,
        Sequence: 0,
        NumberOfChips: 125,
        Color: '#0057B8',
        ItemID: 2,
        Price: 23,
        NumberOfMinutes: 0,
        UpSellID: 4,
      },
      {
        IsBestValue: false,
        CategoryID: 0,
        OriginalPrice: 29,
        Sequence: 0,
        NumberOfChips: 170,
        Color: '#0057B8',
        ItemID: 4,
        Price: 29,
        NumberOfMinutes: 0,
        UpSellID: 3,
      },
      {
        IsBestValue: false,
        CategoryID: 0,
        OriginalPrice: 40,
        Sequence: 0,
        NumberOfChips: 250,
        Color: '#0057B8',
        ItemID: 3,
        Price: 40,
        NumberOfMinutes: 0,
        UpSellID: 5,
      },
      {
        IsBestValue: true,
        CategoryID: 0,
        OriginalPrice: 56,
        Sequence: 0,
        NumberOfChips: 375,
        Color: '#0057B8',
        ItemID: 5,
        Price: 56,
        NumberOfMinutes: 0,
        UpSellID: 6,
      },
      {
        IsBestValue: false,
        CategoryID: 0,
        OriginalPrice: 75,
        Sequence: 0,
        NumberOfChips: 550,
        Color: '#0057B8',
        ItemID: 6,
        Price: 75,
        NumberOfMinutes: 0,
        UpSellID: 7,
      },
      {
        IsBestValue: true,
        CategoryID: 0,
        OriginalPrice: 100,
        Sequence: 0,
        NumberOfChips: 750,
        Color: '#0057B8',
        ItemID: 7,
        Price: 100,
        NumberOfMinutes: 0,
        UpSellID: 0,
      },
    ],
    CategoryList: [
      {
        Sequence: 1,
        Color: '#DC4405',
        CategoryId: 1,
        Label: 'Just Have Fun!',
      },
      {
        Sequence: 2,
        Color: '#DC4405',
        CategoryId: 2,
        Label: 'Better Value!',
      },
      {
        Sequence: 3,
        Color: '#DC4405',
        CategoryId: 3,
        Label: 'Mega Value!',
      },
    ],
    Global: {
      AttractionItemList: [
        {
          IsBestValue: false,
          CategoryID: 0,
          OriginalPrice: 5,
          Sequence: 1,
          NumberOfChips: 1,
          Color: '#DC4405',
          ItemID: 9,
          Price: 5,
          NumberOfMinutes: 0,
          UpSellID: 0,
        },
        {
          IsBestValue: false,
          CategoryID: 0,
          OriginalPrice: 10,
          Sequence: 2,
          NumberOfChips: 2,
          Color: '#DC4405',
          ItemID: 10,
          Price: 10,
          NumberOfMinutes: 0,
          UpSellID: 0,
        },
        {
          IsBestValue: false,
          CategoryID: 0,
          OriginalPrice: 15,
          Sequence: 3,
          NumberOfChips: 3,
          Color: '#DC4405',
          ItemID: 11,
          Price: 15,
          NumberOfMinutes: 0,
          UpSellID: 0,
        },
        {
          IsBestValue: false,
          CategoryID: 0,
          OriginalPrice: 20,
          Sequence: 4,
          NumberOfChips: 4,
          Color: '#DC4405',
          ItemID: 12,
          Price: 20,
          NumberOfMinutes: 0,
          UpSellID: 0,
        },
        {
          IsBestValue: false,
          CategoryID: 0,
          OriginalPrice: 25,
          Sequence: 5,
          NumberOfChips: 5,
          Color: '#DC4405',
          ItemID: 13,
          Price: 25,
          NumberOfMinutes: 0,
          UpSellID: 0,
        },
        {
          IsBestValue: false,
          CategoryID: 0,
          OriginalPrice: 30,
          Sequence: 6,
          NumberOfChips: 6,
          Color: '#DC4405',
          ItemID: 14,
          Price: 30,
          NumberOfMinutes: 0,
          UpSellID: 0,
        },
      ],
      ActivationItem: {
        IsBestValue: false,
        CategoryID: 0,
        OriginalPrice: 3,
        Sequence: 0,
        NumberOfChips: null,
        Color: '#000000',
        ItemID: 8,
        Price: 3,
        NumberOfMinutes: null,
        UpSellID: 0,
      },
      AttractionPrice: 5,
      ActivationFee: 3,
    },
    MenuItemList: [
      {
        IsBestValue: false,
        CategoryID: 1,
        OriginalPrice: 12,
        Sequence: 1,
        NumberOfChips: 60,
        Color: '#0057B8',
        ItemID: 1,
        Price: 12,
        NumberOfMinutes: 0,
        UpSellID: 2,
      },
      {
        IsBestValue: true,
        CategoryID: 1,
        OriginalPrice: 23,
        Sequence: 2,
        NumberOfChips: 125,
        Color: '#0057B8',
        ItemID: 2,
        Price: 23,
        NumberOfMinutes: 0,
        UpSellID: 4,
      },
      {
        IsBestValue: false,
        CategoryID: 2,
        OriginalPrice: 29,
        Sequence: 1,
        NumberOfChips: 170,
        Color: '#0057B8',
        ItemID: 4,
        Price: 29,
        NumberOfMinutes: 0,
        UpSellID: 3,
      },
      {
        IsBestValue: false,
        CategoryID: 2,
        OriginalPrice: 40,
        Sequence: 2,
        NumberOfChips: 250,
        Color: '#0057B8',
        ItemID: 3,
        Price: 40,
        NumberOfMinutes: 0,
        UpSellID: 5,
      },
      {
        IsBestValue: true,
        CategoryID: 2,
        OriginalPrice: 56,
        Sequence: 3,
        NumberOfChips: 375,
        Color: '#0057B8',
        ItemID: 5,
        Price: 56,
        NumberOfMinutes: 0,
        UpSellID: 6,
      },
      {
        IsBestValue: false,
        CategoryID: 3,
        OriginalPrice: 75,
        Sequence: 1,
        NumberOfChips: 550,
        Color: '#0057B8',
        ItemID: 6,
        Price: 75,
        NumberOfMinutes: 0,
        UpSellID: 7,
      },
      {
        IsBestValue: true,
        CategoryID: 3,
        OriginalPrice: 100,
        Sequence: 2,
        NumberOfChips: 750,
        Color: '#0057B8',
        ItemID: 7,
        Price: 100,
        NumberOfMinutes: 0,
        UpSellID: 0,
      },
    ],
  },
};
