export const mockOffersResponse = {
  data: {
    OfferList: [
      {
        ValidFrom: '2019-08-20T00:00:00',
        TermsAndConditions: 'These are the Terms & Conditions',
        Title: 'Buy $20, Get $20 Free!',
        Item: {
          Color: '#000000',
          IsBestValue: false,
          CategoryID: 0,
          NumberOfMinutes: 0,
          Price: 20,
          ItemID: 39,
          NumberOfChips: 200,
          Sequence: 0,
          UpSellID: 0,
          OriginalPrice: 20,
        },
        ImageUrl:
          'https://dave-busters-public.s3.amazonaws.com/offer-images/DB_MobileAppImage_DoubleYourFun_F-01.jpg',
        OfferAmount: 20,
        AutoApply: true,
        Description:
          '$20 Free Game Play* with $20 Power Card® Recharge through 8/27/2019.',
        Disclaimer:
          // tslint:disable-next-line: max-line-length
          '*Promotional. EXPIRES: 8/27/2019. Limit one coupon per customer per Power Card®. Limited to in-app redemption only, not valid for in store redemption. Coupon value may not be divided into multiple Power Cards. Coupon valid for one use only. Minor policies vary by location – please check daveandbusters.com for details. Not valid with any other offers, including Eat & Play Combos, Half Price Games Wednesdays or any Half Price Game promotion. Not valid with Special Events Packages or on Virtual Reality games. NOT FOR RESALE.',
        OfferType: 1550,
        ValidTo: '2020-08-07T00:00:00',
        OfferID: 2,
      },
      {
        ValidFrom: '2019-06-20T00:00:00',
        TermsAndConditions: 'this is a test',
        Title: '$10 OFF $75',
        Item: {
          Color: '#41B6E6',
          IsBestValue: false,
          CategoryID: 0,
          NumberOfMinutes: 0,
          Price: 65,
          ItemID: 73,
          NumberOfChips: 550,
          Sequence: 0,
          UpSellID: 0,
          OriginalPrice: 75,
        },
        ImageUrl:
          'https://dave-busters-public.s3.amazonaws.com/offer-images/DB_Mobile+Images_Double+Game+Play_V1+-+1372.jpg',
        OfferAmount: 10,
        AutoApply: true,
        Description: '$10 OFF Your $75 Purchase',
        Disclaimer: 'this is a test',
        OfferType: 1550,
        ValidTo: '2019-11-21T00:00:00',
        OfferID: 3,
      },
      {
        ValidFrom: '2019-01-01T00:00:00',
        TermsAndConditions: 'These are the Terms & Conditions',
        Title: 'Free $10 Game Play w/ $50 Purchase',
        Item: {
          Color: '#41B6E6',
          IsBestValue: false,
          CategoryID: 0,
          NumberOfMinutes: 0,
          Price: 40,
          ItemID: 74,
          NumberOfChips: 300,
          Sequence: 0,
          UpSellID: 0,
          OriginalPrice: 50,
        },
        ImageUrl:
          'https://dave-busters-public.s3.amazonaws.com/offer-images/DB_Mobile+Images_Double+Game+Play_V1+-+1372.jpg',
        OfferAmount: 10,
        AutoApply: true,
        Description: '$10 Game Play added for FREE to your $50 Purchase',
        Disclaimer:
          // tslint:disable-next-line: max-line-length
          '<FPO> *Craveable Combo does not include tax and gratuity. Offer valid for a limited time only. Unlimited Video Game Play is valid only on day of purchase for non-redemption games and excludes all ticket redemption and Virtual Reality games. Not valid with other offers. Pricing varies by location. Menu selection may vary by location. Participation may vary. Restrictions apply. Void where prohibited. See store for details.',
        OfferType: 1550,
        ValidTo: '2020-12-01T00:00:00',
        OfferID: 4,
      },
      {
        ValidFrom: '2019-06-20T00:00:00',
        TermsAndConditions: 'this is a test',
        Title: '$10 OFF $50',
        Item: {
          Color: '#41B6E6',
          IsBestValue: false,
          CategoryID: 0,
          NumberOfMinutes: 0,
          Price: 40,
          ItemID: 74,
          NumberOfChips: 300,
          Sequence: 0,
          UpSellID: 0,
          OriginalPrice: 50,
        },
        ImageUrl:
          'https://dave-busters-public.s3.amazonaws.com/offer-images/DB_Mobile+Images_Double+Game+Play_V1+-+1372.jpg',
        OfferAmount: 10,
        AutoApply: true,
        Description: '$10 OFF Your $50 Purchase',
        Disclaimer: 'this is a test',
        OfferType: 1550,
        ValidTo: '2020-07-20T00:00:00',
        OfferID: 6,
      },
      {
        ValidFrom: '2019-06-20T00:00:00',
        TermsAndConditions: 'this is a test',
        Title: '20% OFF $75',
        Item: {
          Color: '#41B6E6',
          IsBestValue: false,
          CategoryID: 0,
          NumberOfMinutes: 0,
          Price: 60,
          ItemID: 75,
          NumberOfChips: 550,
          Sequence: 0,
          UpSellID: 0,
          OriginalPrice: 75,
        },
        ImageUrl:
          'https://dave-busters-public.s3.amazonaws.com/offer-images/DB_Mobile+Images_Double+Game+Play_V1+-+1372.jpg',
        OfferAmount: 15,
        AutoApply: true,
        Description: '20% OFF Your $75 Purchase',
        Disclaimer: 'this is a test',
        OfferType: 1550,
        ValidTo: '2020-07-20T00:00:00',
        OfferID: 7,
      },
      {
        ValidFrom: '2019-10-15T00:00:00',
        TermsAndConditions: '',
        Title: '$10 Free Game Play',
        Item: {
          Color: '#000000',
          IsBestValue: false,
          CategoryID: 0,
          NumberOfMinutes: 0,
          Price: 0,
          ItemID: 77,
          NumberOfChips: 48,
          Sequence: 0,
          UpSellID: 0,
          OriginalPrice: 10,
        },
        ImageUrl:
          'https://dave-busters-public.s3.amazonaws.com/offer-images/DB_Mobile+Images_Double+Game+Play_V1+-+1372.jpg',
        OfferAmount: 10,
        AutoApply: true,
        Description: 'Get $10 Free Game Play - No Purchase Necessary!',
        Disclaimer: '',
        OfferType: 1550,
        ValidTo: '2020-03-12T00:00:00',
        OfferID: 8,
      },
      {
        ValidFrom: '2019-08-20T00:00:00',
        TermsAndConditions: 'These are the Terms & Conditions',
        Title: 'Buy $25, Get $25 Free!',
        Item: {
          Color: '#000000',
          IsBestValue: false,
          CategoryID: 0,
          NumberOfMinutes: 0,
          Price: 25,
          ItemID: 80,
          NumberOfChips: 270,
          Sequence: 0,
          UpSellID: 0,
          OriginalPrice: 25,
        },
        ImageUrl:
          'https://dave-busters-public.s3.amazonaws.com/offer-images/DB_MobileAppImage_DoubleYourFun_F-01.jpg',
        OfferAmount: 25,
        AutoApply: true,
        Description:
          '$25 Free Game Play* with $25 Power Card® Recharge through 8/27/2020.',
        Disclaimer:
          // tslint:disable-next-line: max-line-length
          '*Promotional. EXPIRES: 8/27/2020. Limit one coupon per customer per Power Card®. Limited to in-app redemption only, not valid for in store redemption. Coupon value may not be divided into multiple Power Cards. Coupon valid for one use only. Minor policies vary by location – please check daveandbusters.com for details. Not valid with any other offers, including Eat & Play Combos, Half Price Games Wednesdays or any Half Price Game promotion. Not valid with Special Events Packages or on Virtual Reality games. NOT FOR RESALE.',
        OfferType: 1550,
        ValidTo: '2020-08-27T00:00:00',
        OfferID: 10,
      },
    ],
  },
};
