export const mockCheckResponse = {
  CheckDetail: {
    Tax: 3.1,
    EmployeeNumber: 103,
    StoreID: 68,
    Due: 61.75,
    GroupNumber: 1,
    SubTotal: 75.65,
    CheckSequence: 496942432,
    RevenueCenter: 10,
    Other: 0,
    CheckOpenTime: '2019-12-17T08:51:00.51-06:00',
    GuestCount: 0,
    CardNumber: 0,
    CheckNumber: 56,
    Payment: 17,
    CheckDetailLines: [
      {
        Seat: 1,
        Amount: 2.99,
        Description: 'DIET COKE',
        LineNumber: 1,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 2.99,
        Description: 'DR PEPPER',
        LineNumber: 2,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 3.99,
        Description: 'RED BULL',
        LineNumber: 3,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 3.99,
        Description: 'RTBEER FLOAT',
        LineNumber: 4,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 2.99,
        Description: 'GINGER ALE',
        LineNumber: 5,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 3.99,
        Description: 'COKE FLOAT',
        LineNumber: 6,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 2.99,
        Description: 'CLUB SODA',
        LineNumber: 7,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 3.99,
        Description: 'RTBEER FLOAT',
        LineNumber: 8,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 3.99,
        Description: 'SGFR RED BULL',
        LineNumber: 9,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 2.99,
        Description: 'COKE ZERO',
        LineNumber: 10,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 2.79,
        Description: 'TONIC',
        LineNumber: 11,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 3.99,
        Description: 'RTBEER FLOAT',
        LineNumber: 12,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 3.99,
        Description: 'COKE FLOAT',
        LineNumber: 13,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 2.99,
        Description: 'COKE',
        LineNumber: 14,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 2.99,
        Description: 'DR PEPPER',
        LineNumber: 15,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 10,
        Description: 'KIOSK RCH $10 PC',
        LineNumber: 16,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 0,
        Description: null,
        LineNumber: 17,
        DetailType: 'Reference',
        Quantity: 0,
        Reference: '26311882',
      },
      {
        Seat: 1,
        Amount: 10,
        Description: 'KIOSK RCH $10 PC',
        LineNumber: 18,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 0,
        Description: null,
        LineNumber: 19,
        DetailType: 'Reference',
        Quantity: 0,
        Reference: '26311882',
      },
      {
        Seat: 1,
        Amount: 2,
        Description: 'KIOSK SUPER 10',
        LineNumber: 20,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 0,
        Description: null,
        LineNumber: 21,
        DetailType: 'Reference',
        Quantity: 0,
        Reference: '26311882',
      },
      {
        Seat: 1,
        Amount: -10,
        Description: 'G100-02_10FOR10',
        LineNumber: 22,
        DetailType: 'Discount',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 5,
        Description: 'Kiosk Visa',
        LineNumber: 23,
        DetailType: 'Tender',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 0,
        Description: null,
        LineNumber: 24,
        DetailType: 'Reference',
        Quantity: 0,
        Reference: 'ABC123',
      },
      {
        Seat: 0,
        Amount: 0,
        Description: null,
        LineNumber: 25,
        DetailType: 'Extensibility',
        Quantity: 0,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 10,
        Description: 'KIOSK RCH $10 PC',
        LineNumber: 26,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 0,
        Description: null,
        LineNumber: 27,
        DetailType: 'Reference',
        Quantity: 0,
        Reference: '26311882',
      },
      {
        Seat: 1,
        Amount: 10,
        Description: 'KIOSK RCH $10 PC',
        LineNumber: 28,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 0,
        Description: null,
        LineNumber: 29,
        DetailType: 'Reference',
        Quantity: 0,
        Reference: '26311882',
      },
      {
        Seat: 1,
        Amount: 2,
        Description: 'KIOSK SUPER 10',
        LineNumber: 30,
        DetailType: 'MenuItem',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 0,
        Description: null,
        LineNumber: 31,
        DetailType: 'Reference',
        Quantity: 0,
        Reference: '26311882',
      },
      {
        Seat: 1,
        Amount: -10,
        Description: 'G100-02_10FOR10',
        LineNumber: 32,
        DetailType: 'Discount',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 12,
        Description: 'Kiosk Visa',
        LineNumber: 33,
        DetailType: 'Tender',
        Quantity: 1,
        Reference: null,
      },
      {
        Seat: 1,
        Amount: 0,
        Description: null,
        LineNumber: 34,
        DetailType: 'Reference',
        Quantity: 0,
        Reference: 'ABC123',
      },
      {
        Seat: 0,
        Amount: 0,
        Description: null,
        LineNumber: 35,
        DetailType: 'Extensibility',
        Quantity: 0,
        Reference: null,
      },
    ],
    PayCode: '423N4G',
    TableNumber: 12,
    StatusID: 1,
  },
};
