export enum POWERCARD_TRANSACTION_STATE {
  AUTHORIZED = 'AUTHORIZED',
  ACTIVATING_VIRTUAL_POWERCARD = 'ACTIVATING_VIRTUAL_POWERCARD',
  CREATING_VIRTUAL_POWERCARD = 'CREATING_VIRTUAL_POWERCARDS',
  UPDATING_CUSTOMER = 'UPDATING_CUSTOMER',
  RECHARGING_POWERCARD = 'RECHARGING_POWERCARD',
  REDEEMING_OFFER = 'REDEEMING_OFFER',
  CREATING_POWERCARD_SNAPSHOT = 'CREATING_POWERCARD_SNAPSHOT',
  VOIDING_TRANSACTION = 'VOIDING_TRANSACTION',
}
