export const mockCheckUpdate = {
  checkOpenTime: '2020-03-03T19:44:51.000Z',
  other: 0,
  payCode: '2ZRPP2',
  payment: 0,
  storeId: 68,
  subTotal: 429.08,
  tax: 25.75,
  total: 454.83,
  rewardPoints: null,
  lineItems: [
    {
      amount: 10.99,
      description: 'PRETZEL DOGS',
      itemType: 'MENU_ITEM',
      lineNumber: 1,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 10.99,
      description: 'PRETZEL DOGS',
      itemType: 'MENU_ITEM',
      lineNumber: 4,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 17.99,
      description: 'GRILL SIRLOIN',
      itemType: 'MENU_ITEM',
      lineNumber: 5,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 10.99,
      description: 'PRETZEL DOGS',
      itemType: 'MENU_ITEM',
      lineNumber: 6,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 17.99,
      description: 'GRILL SIRLOIN',
      itemType: 'MENU_ITEM',
      lineNumber: 7,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 13.99,
      description: 'BBBACON BURG',
      itemType: 'MENU_ITEM',
      lineNumber: 8,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 10.99,
      description: 'PRETZEL DOGS',
      itemType: 'MENU_ITEM',
      lineNumber: 9,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 17.99,
      description: 'GRILL SIRLOIN',
      itemType: 'MENU_ITEM',
      lineNumber: 10,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 13.99,
      description: 'BBBACON BURG',
      itemType: 'MENU_ITEM',
      lineNumber: 11,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 2.99,
      description: 'COKE',
      itemType: 'MENU_ITEM',
      lineNumber: 12,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 10.99,
      description: 'PRETZEL DOGS',
      itemType: 'MENU_ITEM',
      lineNumber: 13,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 17.99,
      description: 'GRILL SIRLOIN',
      itemType: 'MENU_ITEM',
      lineNumber: 14,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 13.99,
      description: 'BBBACON BURG',
      itemType: 'MENU_ITEM',
      lineNumber: 15,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 2.99,
      description: 'COKE',
      itemType: 'MENU_ITEM',
      lineNumber: 16,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 7.79,
      description: 'CROWN ROYAL',
      itemType: 'MENU_ITEM',
      lineNumber: 17,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 10.99,
      description: 'PRETZEL DOGS',
      itemType: 'MENU_ITEM',
      lineNumber: 18,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 17.99,
      description: 'GRILL SIRLOIN',
      itemType: 'MENU_ITEM',
      lineNumber: 19,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 13.99,
      description: 'BBBACON BURG',
      itemType: 'MENU_ITEM',
      lineNumber: 20,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 2.99,
      description: 'COKE',
      itemType: 'MENU_ITEM',
      lineNumber: 21,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 7.79,
      description: 'CROWN ROYAL',
      itemType: 'MENU_ITEM',
      lineNumber: 22,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 2.99,
      description: 'DR PEPPER',
      itemType: 'MENU_ITEM',
      lineNumber: 23,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 10.99,
      description: 'PRETZEL DOGS',
      itemType: 'MENU_ITEM',
      lineNumber: 24,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 17.99,
      description: 'GRILL SIRLOIN',
      itemType: 'MENU_ITEM',
      lineNumber: 25,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 13.99,
      description: 'BBBACON BURG',
      itemType: 'MENU_ITEM',
      lineNumber: 26,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 2.99,
      description: 'COKE',
      itemType: 'MENU_ITEM',
      lineNumber: 27,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 7.79,
      description: 'CROWN ROYAL',
      itemType: 'MENU_ITEM',
      lineNumber: 28,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 2.99,
      description: 'DR PEPPER',
      itemType: 'MENU_ITEM',
      lineNumber: 29,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 6.49,
      description: 'JACK BLACK',
      itemType: 'MENU_ITEM',
      lineNumber: 30,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 10.99,
      description: 'PRETZEL DOGS',
      itemType: 'MENU_ITEM',
      lineNumber: 31,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 17.99,
      description: 'GRILL SIRLOIN',
      itemType: 'MENU_ITEM',
      lineNumber: 32,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 13.99,
      description: 'BBBACON BURG',
      itemType: 'MENU_ITEM',
      lineNumber: 33,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 2.99,
      description: 'COKE',
      itemType: 'MENU_ITEM',
      lineNumber: 34,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 7.79,
      description: 'CROWN ROYAL',
      itemType: 'MENU_ITEM',
      lineNumber: 35,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 2.99,
      description: 'DR PEPPER',
      itemType: 'MENU_ITEM',
      lineNumber: 36,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 6.49,
      description: 'JACK BLACK',
      itemType: 'MENU_ITEM',
      lineNumber: 37,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 10.99,
      description: 'PRETZEL DOGS',
      itemType: 'MENU_ITEM',
      lineNumber: 38,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 17.99,
      description: 'GRILL SIRLOIN',
      itemType: 'MENU_ITEM',
      lineNumber: 39,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 13.99,
      description: 'BBBACON BURG',
      itemType: 'MENU_ITEM',
      lineNumber: 40,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 2.99,
      description: 'COKE',
      itemType: 'MENU_ITEM',
      lineNumber: 41,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 7.79,
      description: 'CROWN ROYAL',
      itemType: 'MENU_ITEM',
      lineNumber: 42,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 2.99,
      description: 'DR PEPPER',
      itemType: 'MENU_ITEM',
      lineNumber: 43,
      quantity: 1,
      seat: 0,
    },
    {
      amount: 6.49,
      description: 'JACK BLACK',
      itemType: 'MENU_ITEM',
      lineNumber: 44,
      quantity: 1,
      seat: 0,
    },
  ],
};
