import { CHECK_LINE_ITEM_TYPE } from '@open-commerce/data-objects';
import { Receipt, ReceiptLineItem } from '@open-commerce/data-objects';

const date = new Date('December 1, 2020 10:24:00');

export const mockLineItems = [
  {
    id: 1,
    seat: 1,
    amount: 2.99,
    description: 'DR PEPPER',
    lineNumber: 1,
    itemType: CHECK_LINE_ITEM_TYPE.MENU_ITEM,
    quantity: 1,
    reference: null,
    createdAt: date,
    updatedAt: date,
  },
  {
    id: 2,
    seat: 1,
    amount: 2,
    description: 'DR PEPPER',
    lineNumber: 2,
    itemType: CHECK_LINE_ITEM_TYPE.REFERENCE,
    quantity: 1,
    reference: 'mock reference',
    createdAt: date,
    updatedAt: date,
  },
  {
    id: 3,
    seat: 1,
    amount: 5,
    description: 'tip',
    lineNumber: 3,
    itemType: CHECK_LINE_ITEM_TYPE.TIP,
    quantity: 1,
    reference: null,
    createdAt: date,
    updatedAt: date,
  },
  {
    id: 4,
    seat: 1,
    amount: 2,
    description: 'mastercard',
    lineNumber: 4,
    itemType: CHECK_LINE_ITEM_TYPE.TENDER,
    quantity: 1,
    reference: null,
    createdAt: date,
    updatedAt: date,
  },
  {
    id: 5,
    seat: 1,
    amount: 2,
    description: 'visa',
    lineNumber: 5,
    itemType: CHECK_LINE_ITEM_TYPE.TENDER,
    quantity: 1,
    reference: null,
    createdAt: date,
    updatedAt: date,
  },
  {
    id: 6,
    seat: 1,
    amount: 2,
    description: 'unknown',
    lineNumber: 6,
    itemType: CHECK_LINE_ITEM_TYPE.TENDER,
    quantity: 1,
    reference: null,
    createdAt: date,
    updatedAt: date,
  },
] as ReceiptLineItem[];

export const mockReceipt = {
  id: 1,
  total: 100,
  rewardPoints: 100,
  transactionUuid: 'mock-transaction-uuid',
  checkOpenTime: date,
  tax: 3.1,
  employeeNumber: 103,
  storeId: 1,
  due: 61.75,
  groupNumber: 1,
  subTotal: 75.65,
  checkSequence: 496942432,
  revenueCenter: 10,
  other: 0,
  guestCount: 0,
  checkNumber: 56,
  payment: 17,
  payCode: '423N4G',
  tableNumber: 12,
  lineItems: mockLineItems,
} as Receipt;
