export const ADMIN_SERVICE_TOKEN = 'ADMIN_SERVICE_TOKEN';
export const FEATURE_REPOSITORY_TOKEN = 'FEATURE_REPOSITORY_TOKEN';
export const FEATURE_LOCATION_REPOSITORY_TOKEN =
  'FEATURE_LOCATION_REPOSITORY_TOKEN';
export const LOCATION_REPOSITORY_TOKEN = 'LOCATION_REPOSITORY_TOKEN';
