export const DEFAULT_TIMEZONE = 'America/Chicago';
export const POWERCARD_REPOSITORY_TOKEN = 'POWERCARD_REPOSITORY_TOKEN';
export const RATING_REPOSITORY_TOKEN = 'RATING_REPOSITORY_TOKEN';
export const POWERCARD_IMAGE_PACK_REPOSITORY_TOKEN =
  'POWERCARD_IMAGE_PACK_REPOSITORY_TOKEN';
export const DB_CONNECTION_TOKEN = 'DB_CONNECTION_TOKEN';
export const TEST_DB_CONNECTION_TOKEN = 'TEST_DB_CONNECTION_TOKEN';
export const TEST_POWERCARD_REPOSITORY_TOKEN =
  'TEST_POWERCARD_REPOSITORY_TOKEN';
export const TRANSACTION_SERVICE_TOKEN = 'TRANSACTION_SERVICE_TOKEN';
export const CUSTOMER_SERVICE_TOKEN = 'CUSTOMER_SERVICE_TOKEN';
export const MOBILE_PASS_SERVICE_TOKEN = 'MOBILE_PASS_SERVICE_TOKEN';
export const POWERCARD_BALANCE_SNAPSHOT_REPOSITORY_TOKEN =
  'POWERCARD_BALANCE_SNAPSHOT_REPOSITORY_TOKEN';
export const TRANSACTION_REPOSITORY_TOKEN = 'TRANSACTION_REPOSITORY_TOKEN';
export const OFFER_REDEMPTION_REPOSITORY_TOKEN =
  'OFFER_REDEMPTION_REPOSITORY_TOKEN';
export const RECEIPT_REPOSITORY_TOKEN = 'RECEIPT_REPOSITORY_TOKEN';
export const NOTIFICATION_SERVICE_CLIENT_TOKEN =
  'NOTIFICATION_SERVICE_CLIENT_TOKEN';
export const TABLE_GUID_REPOSITORY_TOKEN = 'TABLE_GUID_REPOSITORY_TOKEN';
export const RABBITMQ_SERVICE_TOKEN = 'RABBITMQ_SERVICE_TOKEN';
export const RECEIPT_EMAIL_BUILDER_TOKEN = 'RECEIPT_EMAIL_BUILDER_TOKEN';
export const PROMO_IMAGE_REPOSITORY_TOKEN = 'PROMO_IMAGE_REPOSITORY_TOKEN';
