export const POWERCARD_BALANCES_SERVICE_CONFIG =
  'POWERCARD_BALANCES_SERVICE_CONFIG';
export const MARS_SERVICE_CONFIG = 'MARS_SERVICE_CONFIG';
export const MARS_CACHING_SERVICE_CONFIG = 'MARS_CACHING_SERVICE_CONFIG';
export const POWERCARD_SERVICE_CONFIG = 'POWERCARD_SERVICE_CONFIG';
export const PAY_ANYWHERE_CONFIG = 'PAY_ANYWHERE_CONFIG';
export const ADMIN_SERVICE_CONFIG = 'ADMIN_SERVICE_CONFIG';
export const ENABLE_CONFIG_LOGGING = 'ENABLE_CONFIG_LOGGING';
